version: "3.9"

services:
  django:
    container_name: django
    build:
        context: ./backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
        - ./backend:/app/backend
    ports:
        - 8000:8000

  frontend:
    container_name: frontend
    build:
        context: ./frontend
    command: sh -c "npm run dev -- --host"
    volumes:
        - ./frontend:/app/frontend
    ports:
        - 5173:5173