version: "3.9"

services:
  solr:
    container_name: meic_solr
    image: solr:9.3
    ports:
        - 8983:8983
    command: solr-precreate causes
    volumes:
        - ${PWD}/datasets/generated:/data

  django:
    container_name: django
    build:
        context: ./backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
        - ./backend:/app/backend
    ports:
        - 8000:8000

  frontend:
    container_name: frontend
    build:
        context: ./frontend
    command: sh -c "npm run dev -- --host"
    volumes:
        - ./frontend:/app/frontend
    ports:
        - 5173:5173